#include "website.h"


const char webpage[] =
"<!DOCTYPE html>"
"<html lang='sk'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 e-Vizitka</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0;}"
"body{"
"font-family:'Segoe UI',Arial,sans-serif;"
"background:linear-gradient(135deg,#0f2027,#203a43,#2c5364);"
"min-height:100vh;display:flex;align-items:center;justify-content:center;"
"padding:30px 0;"
"}"
".app{width:620px;display:flex;flex-direction:column;gap:16px;}"
".panel{background:white;border-radius:16px;box-shadow:0 8px 32px rgba(0,0,0,0.3);overflow:hidden;}"
".panel-header{"
"background:linear-gradient(135deg,#2c5364,#203a43);"
"padding:14px 20px;display:flex;align-items:center;gap:10px;"
"}"
".panel-header h2{color:white;font-size:15px;font-weight:600;margin:0;}"
".panel-header .icon{font-size:18px;}"
".panel-body{padding:20px;}"
".preview-panel .panel-body{display:flex;flex-direction:column;align-items:center;gap:10px;}"
".epaper-wrap{"
"background:#8a8a70;border-radius:10px;padding:12px;"
"box-shadow:inset 0 2px 8px rgba(0,0,0,0.4),0 4px 12px rgba(0,0,0,0.2);"
"}"
".epaper-inner{background:#e8e8d8;border-radius:4px;padding:3px;}"
"#displayCanvas{"
"display:block;border:1px solid #999;image-rendering:pixelated;"
"width:296px;height:152px;cursor:crosshair;border-radius:2px;"
"}"
".info-bar{font-size:11px;color:#888;background:#f5f5f5;padding:6px 12px;border-radius:20px;}"
".btn-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;}"
".btn{"
"padding:10px 8px;border:none;border-radius:8px;"
"font-size:12px;font-weight:500;cursor:pointer;transition:all 0.2s;"
"display:flex;align-items:center;justify-content:center;gap:5px;"
"}"
".btn-primary{background:#2c5364;color:white;}"
".btn-primary:hover{background:#1a3a4a;transform:translateY(-1px);}"
".btn-success{background:#1a6b3a;color:white;}"
".btn-success:hover{background:#0f4a28;transform:translateY(-1px);}"
".btn-warning{background:#7a5c00;color:white;}"
".btn-warning:hover{background:#5a4200;transform:translateY(-1px);}"
".btn-neutral{background:#f0f0f0;color:#333;border:1px solid #ddd;}"
".btn-neutral:hover{background:#e0e0e0;transform:translateY(-1px);}"
".btn:active{transform:translateY(0px)!important;}"
".upload-area{"
"border:2px dashed #ccc;border-radius:10px;padding:16px;"
"display:flex;align-items:center;gap:12px;flex-wrap:wrap;transition:border-color 0.2s;"
"}"
".upload-area:hover{border-color:#2c5364;}"
"input[type=file]{font-size:12px;color:#555;flex:1;}"
".status-bar{"
"padding:10px 14px;border-radius:8px;font-size:13px;font-weight:600;"
"background:#f0f7ff;color:#2c5364;border-left:3px solid #2c5364;"
"min-height:38px;display:flex;align-items:center;"
"}"
".form-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px;}"
".form-group{display:flex;flex-direction:column;gap:4px;}"
".form-group label{font-size:11px;color:#888;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;}"
".form-group input,.form-group select{"
"padding:8px 10px;border:1px solid #ddd;border-radius:8px;"
"font-size:13px;color:#333;transition:border-color 0.2s;"
"}"
".form-group input:focus,.form-group select:focus{outline:none;border-color:#2c5364;}"
".type-selector{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:4px;}"
".type-btn{"
"padding:6px 12px;border:2px solid #ddd;border-radius:20px;"
"font-size:12px;background:white;color:#555;cursor:pointer;transition:all 0.2s;"
"}"
".type-btn.active{border-color:#2c5364;background:#2c5364;color:white;}"
".type-btn:hover:not(.active){border-color:#2c5364;color:#2c5364;}"
".color-selector{display:flex;gap:8px;align-items:center;}"
".color-btn{width:28px;height:28px;border-radius:50%;border:3px solid transparent;cursor:pointer;transition:all 0.2s;}"
".color-btn.black{background:#111;}"
".color-btn.white{background:#fff;border:3px solid #ddd;}"
".color-btn.active{border-color:#2c5364;transform:scale(1.2);}"
".draw-btn-row{display:flex;justify-content:flex-end;margin-top:14px;}"
".section-label{font-size:11px;color:#888;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:8px;}"
".divider{height:1px;background:#f0f0f0;margin:14px 0;}"
"</style>"
"</head>"
"<body>"
"<div class='app'>"

"<div style='text-align:center;padding:10px 0;'>"
"<h1 style='color:white;font-size:24px;font-weight:700;letter-spacing:1px;'>ESP32 e-Vizitka</h1>"
"<p style='color:rgba(255,255,255,0.6);font-size:13px;margin-top:4px;'>Správa e-paper displeja</p>"
"</div>"

"<div class='panel preview-panel'>"
"<div class='panel-header'><span class='icon'>🖥</span><h2>Živý náhľad displeja</h2></div>"
"<div class='panel-body'>"
"<div class='epaper-wrap'><div class='epaper-inner'>"
"<canvas id='displayCanvas' width='296' height='152'></canvas>"
"</div></div>"
"<div class='info-bar' id='info'>Načítavam...</div>"
"</div>"
"</div>"

"<div class='panel'>"
"<div class='panel-header'><span class='icon'>⚙️</span><h2>Ovládanie displeja</h2></div>"
"<div class='panel-body'>"
"<p class='section-label'>Zobrazenie a napájanie</p>"
"<div class='btn-grid'>"
"<button class='btn btn-success' onclick='showOnDisplay()'>📺 Zobraziť na displeji</button>"
"<button class='btn btn-primary' onclick='refreshDisplay()'>🔄 Obnoviť náhľad</button>"
"<button class='btn btn-warning' onclick='sleepDisplay()'>💤 Vypnúť displej</button>"
"</div>"
"<div class='divider'></div>"
"<p class='section-label'>Správa obsahu</p>"
"<div class='btn-grid'>"
"<button class='btn btn-primary' onclick='clearWhite()'>⬜ Biele pozadie</button>"
"<button class='btn btn-primary' onclick='clearBlack()'>⬛ Čierne pozadie</button>"
"<button class='btn btn-neutral' onclick='rotateBuffer()'>↩ Otočiť o 90°</button>"
"<button class='btn btn-neutral' onclick='undo()'>↺ Vrátiť späť</button>"
"<button class='btn btn-primary' onclick='loadBmp()'>🖼 Načítať obrázok</button>"
"</div>"
"</div>"
"</div>"

"<div class='panel'>"
"<div class='panel-header'><span class='icon'>📁</span><h2>Nahrať obrázok</h2></div>"
"<div class='panel-body'>"
"<div class='upload-area'>"
"<input type='file' id='fileInput' accept='.bmp'>"
"<button class='btn btn-success' style='white-space:nowrap;' onclick='uploadBmp()'>⬆ Odoslať súbor</button>"
"</div>"
"</div>"
"</div>"

"<div class='status-bar' id='status'>Pripravený</div>"

"<div class='panel'>"
"<div class='panel-header'><span class='icon'>✏️</span><h2>Kresliť na displej</h2></div>"
"<div class='panel-body'>"
"<p class='section-label'>Vyber typ prvku</p>"
"<div class='type-selector'>"
"<button class='type-btn active' onclick='selectType(\"line\",this)'>Čiara</button>"
"<button class='type-btn' onclick='selectType(\"rect\",this)'>Obdĺžnik</button>"
"<button class='type-btn' onclick='selectType(\"circle\",this)'>Kruh</button>"
"<button class='type-btn' onclick='selectType(\"string\",this)'>Text</button>"
"<button class='type-btn' onclick='selectType(\"number\",this)'>Celé číslo</button>"
"<button class='type-btn' onclick='selectType(\"decimal\",this)'>Desatinné číslo</button>"
"</div>"
"<div class='divider'></div>"
"<div style='display:flex;align-items:center;gap:16px;margin-bottom:4px;'>"
"<p class='section-label' style='margin:0;'>Farba prvku</p>"
"<div class='color-selector'>"
"<div class='color-btn black active' id='colorBlack' onclick='selectColor(0)'></div>"
"<div class='color-btn white' id='colorWhite' onclick='selectColor(1)'></div>"
"</div>"
"</div>"
"<div id='shapeFields' class='form-grid'></div>"
"<div class='draw-btn-row'>"
"<button class='btn btn-success' style='padding:10px 24px;' onclick='drawShape()'>✏️ Pridať na displej</button>"
"</div>"
"</div>"
"</div>"

"</div>"

"<script>"
"const BUF_W=152,BUF_H=296;"
"const DISP_W=296,DISP_H=152;"
"const canvas=document.getElementById('displayCanvas');"
"const ctx=canvas.getContext('2d');"
"let clickCount=0;"
"let selectedType='line';"
"let selectedColor=0;"

"function selectType(type,btn){"
"  selectedType=type;"
"  document.querySelectorAll('.type-btn').forEach(b=>b.classList.remove('active'));"
"  btn.classList.add('active');"
"  clickCount=0;"
"  updateFields();"
"}"

"function selectColor(c){"
"  selectedColor=c;"
"  document.getElementById('colorBlack').classList.toggle('active',c===0);"
"  document.getElementById('colorWhite').classList.toggle('active',c===1);"
"}"

"async function undo(){"
"  const r=await fetch('/undo',{method:'POST'});"
"  if(r.ok){setStatus('✓ Posledná akcia bola vrátená späť');refreshDisplay();}"
"  else setStatus('✗ Nepodarilo sa vrátiť späť');"
"}"

"async function refreshDisplay(){"
"  try{"
"    const r=await fetch('/get_display?t='+Date.now());"
"    if(!r.ok){setInfo('Chyba načítania');return;}"
"    const buf=await r.arrayBuffer();"
"    const data=new Uint8Array(buf);"
"    const img=ctx.createImageData(DISP_W,DISP_H);"
"    const bpr=Math.ceil(BUF_W/8);"
"    for(let by=0;by<BUF_H;by++){"
"      for(let bx=0;bx<BUF_W;bx++){"
"        const dx=by;"
"        const dy=BUF_W-1-bx;"
"        const bi=Math.floor(bx/8)+by*bpr;"
"        const bit=(data[bi]>>(7-(bx%8)))&1;"
"        const c=bit?255:0;"
"        const p=(dy*DISP_W+dx)*4;"
"        img.data[p]=c;img.data[p+1]=c;"
"        img.data[p+2]=c;img.data[p+3]=255;"
"      }"
"    }"
"    ctx.putImageData(img,0,0);"
"    setInfo('Buffer: '+data.length+' B | '+DISP_W+'×'+DISP_H+' px');"
"  }catch(e){setInfo('Chyba: '+e.message);}"
"}"

"canvas.addEventListener('click',function(e){"
"  const rect=canvas.getBoundingClientRect();"
"  const scaleX=DISP_W/rect.width;"
"  const scaleY=DISP_H/rect.height;"
"  const bx=Math.floor((e.clientX-rect.left)*scaleX);"
"  const by=Math.floor((e.clientY-rect.top)*scaleY);"
"  if(clickCount===0){"
"    const ex1=document.getElementById('f_x1');"
"    const ey1=document.getElementById('f_y1');"
"    if(ex1) ex1.value=bx;"
"    if(ey1) ey1.value=by;"
"    setStatus('1. bod: X='+bx+' Y='+by+' — klikni pre 2. bod');"
"    clickCount=1;"
"  }else{"
"    const ex2=document.getElementById('f_x2');"
"    const ey2=document.getElementById('f_y2');"
"    const er=document.getElementById('f_radius');"
"    if(ex2) ex2.value=bx;"
"    if(ey2) ey2.value=by;"
"    if(er){"
"      const x1v=parseInt(document.getElementById('f_x1').value||0);"
"      const y1v=parseInt(document.getElementById('f_y1').value||0);"
"      er.value=Math.floor(Math.sqrt((bx-x1v)*(bx-x1v)+(by-y1v)*(by-y1v)));"
"    }"
"    setStatus('2. bod: X='+bx+' Y='+by+' — pripravené na kreslenie');"
"    clickCount=0;"
"  }"
"});"

"async function clearWhite(){"
"  await fetch('/clear_white',{method:'POST'});"
"  setStatus('✓ Displej bol vyčistený — biele pozadie');refreshDisplay();"
"}"
"async function clearBlack(){"
"  await fetch('/clear_black',{method:'POST'});"
"  setStatus('✓ Displej bol vyčistený — čierne pozadie');refreshDisplay();"
"}"
"async function loadBmp(){"
"  setStatus('Načítavam obrázok do pamäte...');"
"  const r=await fetch('/load_bmp',{method:'POST'});"
"  if(r.ok){setStatus('✓ Obrázok bol načítaný do pamäte');refreshDisplay();}"
"  else setStatus('✗ Nepodarilo sa načítať obrázok');"
"}"
"async function showOnDisplay(){"
"  setStatus('Zobrazujem obsah na displeji...');"
"  const r=await fetch('/draw_bitmap',{method:'POST'});"
"  setStatus(r.ok?'✓ Obsah bol zobrazený na displeji':'✗ Nepodarilo sa zobraziť obsah');"
"}"
"async function sleepDisplay(){"
"  await fetch('/sleep',{method:'POST'});"
"  setStatus('💤 Displej bol vypnutý');"
"}"
"async function rotateBuffer(){"
"  setStatus('Otáčam obsah displeja...');"
"  const r=await fetch('/rotate_buffer',{method:'POST'});"
"  if(r.ok){setStatus('✓ Obsah bol otočený o 90°');refreshDisplay();}"
"  else setStatus('✗ Nepodarilo sa otočiť obsah');"
"}"
"async function uploadBmp(){"
"  const file=document.getElementById('fileInput').files[0];"
"  if(!file){alert('Najprv vyber .bmp súbor');return;}"
"  setStatus('Odosielam súbor...');"
"  const fd=new FormData();"
"  fd.append('file',file);"
"  const r=await fetch('/upload',{method:'POST',body:fd});"
"  if(r.ok){"
"    setStatus('✓ Súbor bol úspešne odoslaný');"
"    document.getElementById('fileInput').value='';"
"  }"
"  else setStatus('✗ Nepodarilo sa odoslať súbor');"
"}"

"const fieldDefs={"
"  line:[{id:'x1',label:'Začiatok X'},{id:'y1',label:'Začiatok Y'},"
"        {id:'x2',label:'Koniec X'},{id:'y2',label:'Koniec Y'},"
"        {id:'width',label:'Hrúbka čiary',type:'select',opts:['1','2','3','4','5','6','7','8']},"
"        {id:'style',label:'Štýl čiary',type:'select',opts:['Plná','Bodkovaná']}],"
"  rect:[{id:'x1',label:'Ľavý horný X'},{id:'y1',label:'Ľavý horný Y'},"
"        {id:'x2',label:'Pravý dolný X'},{id:'y2',label:'Pravý dolný Y'},"
"        {id:'width',label:'Hrúbka okraja',type:'select',opts:['1','2','3','4','5','6','7','8']},"
"        {id:'filled',label:'Výplň',type:'select',opts:['Nie','Áno']}],"
"  circle:[{id:'x1',label:'Stred X'},{id:'y1',label:'Stred Y'},"
"          {id:'radius',label:'Polomer'},"
"          {id:'width',label:'Hrúbka okraja',type:'select',opts:['1','2','3','4','5','6','7','8']},"
"          {id:'filled',label:'Výplň',type:'select',opts:['Nie','Áno']}],"
"  string:[{id:'x1',label:'Pozícia X'},{id:'y1',label:'Pozícia Y'},"
"          {id:'text',label:'Text na zobrazenie',type:'text'},"
"          {id:'font',label:'Veľkosť písma',type:'select',opts:['8','12','16','20','24']}],"
"  number:[{id:'x1',label:'Pozícia X'},{id:'y1',label:'Pozícia Y'},"
"          {id:'number',label:'Číslo na zobrazenie'},"
"          {id:'font',label:'Veľkosť písma',type:'select',opts:['8','12','16','20','24']}],"
"  decimal:[{id:'x1',label:'Pozícia X'},{id:'y1',label:'Pozícia Y'},"
"           {id:'number',label:'Hodnota × 100 (napr. 314 = 3.14)'},"
"           {id:'digit',label:'Počet desatinných miest'},"
"           {id:'font',label:'Veľkosť písma',type:'select',opts:['8','12','16','20','24']}]"
"};"

"function updateFields(){"
"  const fields=fieldDefs[selectedType];"
"  let html='';"
"  for(const f of fields){"
"    const isText=f.type==='text';"
"    const span=isText?'grid-column:1/-1':'';"
"    html+='<div class=\"form-group\" style=\"'+span+'\">';"
"    html+='<label>'+f.label+'</label>';"
"    if(f.type==='select'){"
"      html+='<select id=\"f_'+f.id+'\">';"
"      for(let i=0;i<f.opts.length;i++){"
"        html+='<option value=\"'+i+'\">'+f.opts[i]+'</option>';"
"      }"
"      html+='</select>';"
"    }else if(isText){"
"      html+='<input type=\"text\" id=\"f_'+f.id+'\" placeholder=\"Zadaj text...\">';"
"    }else{"
"      html+='<input type=\"number\" id=\"f_'+f.id+'\" value=\"0\" min=\"0\" max=\"300\">';"
"    }"
"    html+='</div>';"
"  }"
"  document.getElementById('shapeFields').innerHTML=html;"
"}"

"function getField(id,def){"
"  const el=document.getElementById('f_'+id);"
"  if(!el) return def!==undefined?def:0;"
"  return el.value;"
"}"

"async function drawShape(){"
"  const params=new URLSearchParams();"
"  params.append('type',selectedType);"
"  params.append('color',selectedColor);"
"  params.append('x1',getField('x1',0));"
"  params.append('y1',getField('y1',0));"
"  params.append('x2',getField('x2',0));"
"  params.append('y2',getField('y2',0));"
"  params.append('radius',getField('radius',0));"
"  params.append('width',parseInt(getField('width',0))+1);"
"  params.append('style',getField('style',0));"
"  params.append('filled',getField('filled',0));"
"  params.append('font',[8,12,16,20,24][parseInt(getField('font',2))]);"
"  params.append('text',getField('text',''));"
"  params.append('number',getField('number',0));"
"  params.append('digit',getField('digit',0));"
"  setStatus('Pridávam prvok na displej...');"
"  const r=await fetch('/draw_shape',{method:'POST',body:params.toString(),"
"    headers:{'Content-Type':'application/x-www-form-urlencoded'}});"
"  if(r.ok){setStatus('✓ Prvok bol úspešne pridaný');refreshDisplay();}"
"  else setStatus('✗ Nepodarilo sa pridať prvok');"
"}"

"function setStatus(m){document.getElementById('status').innerText=m;}"
"function setInfo(m){document.getElementById('info').innerText=m;}"

"updateFields();"
"setInterval(refreshDisplay,3000);"
"refreshDisplay();"
"</script>"
"</body>"
"</html>";
