#include "website.h"

const char webpage[] =
"<!DOCTYPE html>"
"<html lang='sk'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>ESP32 e-Vizitka</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0;}"
"body{"
"font-family:Arial,sans-serif;"
"background:linear-gradient(135deg,#0f2027,#203a43,#2c5364);"
"min-height:100vh;display:flex;align-items:center;justify-content:center;"
"}"
".card{"
"background:white;padding:28px;border-radius:20px;"
"box-shadow:0 15px 40px rgba(0,0,0,0.4);text-align:center;width:560px;"
"}"
"h1{color:#333;margin-bottom:6px;}"
".subtitle{color:#888;font-size:14px;margin-bottom:20px;}"
".epaper-wrap{"
"background:#9a9a80;border-radius:12px;padding:14px;"
"display:inline-block;margin-bottom:16px;"
"box-shadow:inset 0 2px 8px rgba(0,0,0,0.35),0 4px 12px rgba(0,0,0,0.2);"
"}"
".epaper-inner{"
"background:#f0f0e0;border-radius:4px;padding:4px;"
"}"
"#displayCanvas{"
"display:block;border:1px solid #aaa;"
"image-rendering:pixelated;"
"width:296px;height:152px;"
"}"
".info-bar{"
"font-size:11px;color:#aaa;margin-bottom:14px;"
"}"
".controls{"
"display:flex;flex-wrap:wrap;gap:8px;"
"justify-content:center;margin-bottom:14px;"
"}"
"button{"
"padding:9px 16px;border:none;"
"background:#2c5364;color:white;"
"font-size:13px;border-radius:8px;"
"cursor:pointer;transition:background 0.2s;"
"}"
"button:hover{background:#1a3a4a;}"
"button:active{background:#0f2535;}"
".upload-row{"
"display:flex;gap:8px;align-items:center;"
"justify-content:center;margin-bottom:12px;"
"flex-wrap:wrap;"
"}"
"input[type=file]{font-size:13px;color:#555;}"
"#status{"
"min-height:20px;font-size:13px;"
"color:#2c5364;font-weight:bold;"
"}"
"</style>"
"</head>"
"<body>"
"<div class='card'>"
"<h1>ESP32 e-Vizitka</h1>"
"<p class='subtitle'>Živý náhľad image bufferu — 296×152 px</p>"

"<div class='epaper-wrap'>"
"<div class='epaper-inner'>"
"<canvas id='displayCanvas' width='296' height='152'></canvas>"
"</div>"
"</div>"

"<p class='info-bar' id='info'>Načítavam...</p>"

"<div class='controls'>"
"<button onclick='refreshDisplay()'>🔄 Refresh</button>"
"<button onclick='clearWhite()'>⬜ Clear biela</button>"
"<button onclick='clearBlack()'>⬛ Clear čierna</button>"
"<button onclick='loadBmp()'>🖼 Načítať BMP do bufferu</button>"
"<button onclick='showOnDisplay()'>📺 Zobraziť na e-paper</button>"
"<button onclick='sleepDisplay()'>💤 Uspať displej</button>"
"</div>"

"<div class='upload-row'>"
"<input type='file' id='fileInput' accept='.bmp'>"
"<button onclick='uploadBmp()'>⬆ Nahrať BMP</button>"
"</div>"

"<p id='status'></p>"
"</div>"

"<script>"
"const BUF_W=152,BUF_H=296;"
"const DISP_W=296,DISP_H=152;"
"const canvas=document.getElementById('displayCanvas');"
"const ctx=canvas.getContext('2d');"

"async function refreshDisplay(){"
"  try{"
"    const r=await fetch('/get_display?t='+Date.now());"
"    if(!r.ok){setInfo('Chyba načítania bufferu');return;}"
"    const buf=await r.arrayBuffer();"
"    const data=new Uint8Array(buf);"
"    const img=ctx.createImageData(DISP_W,DISP_H);"
"    const bpr=Math.ceil(BUF_W/8);"
"    for(let by=0;by<BUF_H;by++){"
"      for(let bx=0;bx<BUF_W;bx++){"
"        const dx=BUF_H-1-by;"
"        const dy=bx;"
"        const bi=Math.floor(bx/8)+by*bpr;"
"        const bit=(data[bi]>>(7-(bx%8)))&1;"
"        const c=bit?255:0;"
"        const p=(dy*DISP_W+dx)*4;"
"        img.data[p]=c;img.data[p+1]=c;"
"        img.data[p+2]=c;img.data[p+3]=255;"
"      }"
"    }"
"    ctx.putImageData(img,0,0);"
"    setInfo('Buffer: '+data.length+' B | '+DISP_W+'×'+DISP_H+' px');"
"  }catch(e){setInfo('Chyba: '+e.message);}"
"}"

"async function clearWhite(){"
"  await fetch('/clear_white',{method:'POST'});"
"  setStatus('✓ Clear biela');refreshDisplay();"
"}"
"async function clearBlack(){"
"  await fetch('/clear_black',{method:'POST'});"
"  setStatus('✓ Clear čierna');refreshDisplay();"
"}"
"async function loadBmp(){"
"  setStatus('Načítavam BMP do bufferu...');"
"  const r=await fetch('/load_bmp',{method:'POST'});"
"  if(r.ok){setStatus('✓ BMP načítané do bufferu');refreshDisplay();}"
"  else setStatus('✗ Chyba načítania BMP');"
"}"
"async function showOnDisplay(){"
"  setStatus('Zobrazujem...');"
"  const r=await fetch('/draw_bitmap',{method:'POST'});"
"  setStatus(r.ok?'✓ Zobrazené na e-paper':'✗ Chyba zobrazenia');"
"}"
"async function sleepDisplay(){"
"  await fetch('/sleep',{method:'POST'});"
"  setStatus('💤 Displej uspán');"
"}"
"async function uploadBmp(){"
"  const file=document.getElementById('fileInput').files[0];"
"  if(!file){alert('Vyber BMP súbor');return;}"
"  setStatus('Nahrávam BMP...');"
"  const fd=new FormData();"
"  fd.append('file',file);"
"  const r=await fetch('/upload',{method:'POST',body:fd});"
"  if(r.ok){"
"    setStatus('✓ BMP nahraté');"
"    document.getElementById('fileInput').value='';"
"    refreshDisplay();"
"  }"
"  else setStatus('✗ Chyba nahrávania');"
"}"
"function setStatus(m){document.getElementById('status').innerText=m;}"
"function setInfo(m){document.getElementById('info').innerText=m;}"

"setInterval(refreshDisplay,3000);"
"refreshDisplay();"
"</script>"
"</body>"
"</html>";